#!/bin/sh

if [ $# -ne 2 ]; then
  echo "Usage: $0 filename \"line to append\""
  exit 1
fi

filename=$1
line=$2

echo "$line" >> "$filename"

num_lines=$(wc -l < "$filename")

echo "Line appended to '$filename'."
echo "Total number of lines now: $num_lines"
